# Generated by Django 5.2.3 on 2026-02-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_seller_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='app_userint_user_id_068b88_idx',
            old_name='app_userint_user_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='app_userint_product_338218_idx',
            old_name='app_userint_product_id_timestamp_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Debit/Credit Card')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
