# Generated by Django 5.2.3 on 2026-02-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sellerprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of warranty days offered by seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_provided',
            field=models.BooleanField(default=False, help_text='Whether seller provides warranty for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_terms',
            field=models.TextField(blank=True, default='', help_text='Optional warranty terms/notes provided by seller'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], max_length=20)),
                ('reason', models.TextField()),
                ('customer_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('customer_ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='app.order')),
            ],
        ),
    ]
