# Generated by Django 5.2.3 on 2026-02-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
