# Generated by Django 5.2.3 on 2026-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_notification_id'),
        ('app', '0016_notification_product_chatmessage'),
    ]

    operations = [
    ]
